// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQV2BgEZDgxufGi5tpDEH3lz6FJhLKye8',
    appId: '1:318857210338:web:96a65e0712bb19757071bb',
    messagingSenderId: '318857210338',
    projectId: 'index-omnium',
    authDomain: 'index-omnium.firebaseapp.com',
    storageBucket: 'index-omnium.firebasestorage.app',
    measurementId: 'G-2N2QSN1LNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7IsZhvOeVWlmEPdHWdPs4lB1lCYVPNqQ',
    appId: '1:318857210338:android:a78eec5a714f10137071bb',
    messagingSenderId: '318857210338',
    projectId: 'index-omnium',
    storageBucket: 'index-omnium.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCdG512eIWPLcCy_XyJn4Hp_L2AFBOId8',
    appId: '1:318857210338:ios:955b07f61e60e5037071bb',
    messagingSenderId: '318857210338',
    projectId: 'index-omnium',
    storageBucket: 'index-omnium.firebasestorage.app',
    iosBundleId: 'com.example.indexOmniumUiGrid2Or4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCdG512eIWPLcCy_XyJn4Hp_L2AFBOId8',
    appId: '1:318857210338:ios:955b07f61e60e5037071bb',
    messagingSenderId: '318857210338',
    projectId: 'index-omnium',
    storageBucket: 'index-omnium.firebasestorage.app',
    iosBundleId: 'com.example.indexOmniumUiGrid2Or4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQV2BgEZDgxufGi5tpDEH3lz6FJhLKye8',
    appId: '1:318857210338:web:9ad04a06960fd3c17071bb',
    messagingSenderId: '318857210338',
    projectId: 'index-omnium',
    authDomain: 'index-omnium.firebaseapp.com',
    storageBucket: 'index-omnium.firebasestorage.app',
    measurementId: 'G-WKE98CJF6G',
  );
}
